export const serviceConfig = [
    {
      id: 8,
      type: "netflix",
      name: "Netflix",
      image: "/images/netflix.svg",
      squareimage: "/images/netflix-square.svg",
      background: "bg-gradient-to-tl from-red-700/80 via-black/80 to-red-700/80",
      serviceBackground: "bg-gradient-to-br from-red-700/20 to-black",
      alt: "Netflix Logo",
    },
    {
      id: 337,
      type: "disney",
      name: "Disney+",
      image: "/images/disney.svg",
      squareimage: "/images/disney-square.svg",
      background: "bg-gradient-to-b from-black/80 to-blue-600/80",
      serviceBackground: "bg-gradient-to-br from-blue-600/20 to-black",
      alt: "Disney+ Logo",
    },
    {
      id: 1899,
      type: "max",
      name: "HBO Max",
      image: "/images/max.svg",
      squareimage: "/images/max-square.svg",
      background: "bg-gradient-to-r from-white/80 to-purple-400/80",
      serviceBackground: "bg-gradient-to-br from-purple-400/20 to-black",
      alt: "Hbo Max Logo",
    },
    {
      id: 350,
      type: "apple",
      name: "Apple TV+",
      image: "/images/apple.svg",
      squareimage: "/images/apple-square.svg",
      background: "bg-neutral-400/80",
      serviceBackground: "bg-gradient-to-br from-neutral-400/20 to-black",
      alt: "Apple TV+ Logo",
    },
    {
      id: 9,
      type: "prime",
      name: "Amazon Prime Video",
      image: "/images/prime.svg",
      squareimage: "/images/prime-square.svg",
      background: "bg-white/80",
      serviceBackground: "bg-gradient-to-br from-white/20 to-black",
      alt: "Amazon Prime Video Logo",
    },
    {
      id: 15,
      type: "hulu",
      name: "Hulu",
      image: "/images/hulu.svg",
      squareimage: "/images/hulu-square.svg",
      background: "bg-gradient-to-br from-black/80 to-cyan-900/80",
      serviceBackground: "bg-gradient-to-br from-cyan-900/30 to-black",
      alt: "Hulu Logo",
    },
    {
      id: 531,
      type: "paramount",
      name: "Paramount",
      image: "/images/paramount.svg",
      squareimage: "/images/paramount-square.svg",
      background: "bg-gradient-to-br from-white/80 to-blue-200/80",
      serviceBackground: "bg-gradient-to-br from-blue-300/20 to-black",
      alt: "Paramount Logo",
    },
    {
      id: 386,
      type: "peacock",
      name: "Peacock",
      image: "/images/peacock.svg",
      squareimage: "/images/peacock-square.svg",
      background: "bg-gradient-to-br from-white/80 to-neutral-300/80",
      serviceBackground: "bg-gradient-to-br from-neutral-300/20 to-black",
      alt: "Peacock Logo",
    }
  ]
